-- Generated by mappings.fnl replicate-regulation-items!
-- Run: cd <este-dir> && psql -d demo_data -f import.sql
-- (o via (chulos.pick-and-import!))
--
-- Pisa los rows con IDs conflictivos en local con la versión del PR.
-- Patrón: CSV → temp table → DELETE conflicts → INSERT FROM temp.

BEGIN;

-- Disable FK checks para esquivar self-refs (parent_item_id),
-- ancestros faltantes y FK externas no incluidas.
-- Requiere superuser — alcanza para demo_data en local.
SET session_replication_role = replica;

-- workspaces
CREATE TEMP TABLE _stage_workspaces (LIKE workspaces);
\copy _stage_workspaces FROM 'workspaces.txt' WITH (FORMAT text)
DELETE FROM workspaces WHERE id IN (SELECT id FROM _stage_workspaces);
INSERT INTO workspaces SELECT * FROM _stage_workspaces;
DROP TABLE _stage_workspaces;

-- program_categories
CREATE TEMP TABLE _stage_program_categories (LIKE program_categories);
\copy _stage_program_categories FROM 'program_categories.txt' WITH (FORMAT text)
DELETE FROM program_categories WHERE id IN (SELECT id FROM _stage_program_categories);
INSERT INTO program_categories SELECT * FROM _stage_program_categories;
DROP TABLE _stage_program_categories;

-- programs
CREATE TEMP TABLE _stage_programs (LIKE programs);
\copy _stage_programs FROM 'programs.txt' WITH (FORMAT text)
DELETE FROM programs WHERE id IN (SELECT id FROM _stage_programs);
INSERT INTO programs SELECT * FROM _stage_programs;
DROP TABLE _stage_programs;

-- framework_items
CREATE TEMP TABLE _stage_framework_items (LIKE framework_items);
\copy _stage_framework_items FROM 'framework_items.txt' WITH (FORMAT text)
DELETE FROM framework_items WHERE id IN (SELECT id FROM _stage_framework_items);
INSERT INTO framework_items SELECT * FROM _stage_framework_items;
DROP TABLE _stage_framework_items;

-- controls
CREATE TEMP TABLE _stage_controls (LIKE controls);
\copy _stage_controls FROM 'controls.txt' WITH (FORMAT text)
DELETE FROM controls WHERE id IN (SELECT id FROM _stage_controls);
INSERT INTO controls SELECT * FROM _stage_controls;
DROP TABLE _stage_controls;

-- regulations
CREATE TEMP TABLE _stage_regulations (LIKE regulations);
\copy _stage_regulations FROM 'regulations.txt' WITH (FORMAT text)
DELETE FROM regulations WHERE id IN (SELECT id FROM _stage_regulations);
INSERT INTO regulations SELECT * FROM _stage_regulations;
DROP TABLE _stage_regulations;

-- regulation_items
CREATE TEMP TABLE _stage_regulation_items (LIKE regulation_items);
\copy _stage_regulation_items FROM 'regulation_items.txt' WITH (FORMAT text)
DELETE FROM regulation_items WHERE id IN (SELECT id FROM _stage_regulation_items);
INSERT INTO regulation_items SELECT * FROM _stage_regulation_items;
DROP TABLE _stage_regulation_items;

-- policies
CREATE TEMP TABLE _stage_policies (LIKE policies);
\copy _stage_policies FROM 'policies.txt' WITH (FORMAT text)
DELETE FROM policies WHERE id IN (SELECT id FROM _stage_policies);
INSERT INTO policies SELECT * FROM _stage_policies;
DROP TABLE _stage_policies;

-- policy_regulation_item_mappings
CREATE TEMP TABLE _stage_policy_regulation_item_mappings (LIKE policy_regulation_item_mappings);
\copy _stage_policy_regulation_item_mappings FROM 'policy_regulation_item_mappings.txt' WITH (FORMAT text)
DELETE FROM policy_regulation_item_mappings WHERE id IN (SELECT id FROM _stage_policy_regulation_item_mappings);
INSERT INTO policy_regulation_item_mappings SELECT * FROM _stage_policy_regulation_item_mappings;
DROP TABLE _stage_policy_regulation_item_mappings;

-- controls_regulation_items
CREATE TEMP TABLE _stage_controls_regulation_items (LIKE controls_regulation_items);
\copy _stage_controls_regulation_items FROM 'controls_regulation_items.txt' WITH (FORMAT text)
DELETE FROM controls_regulation_items WHERE id IN (SELECT id FROM _stage_controls_regulation_items);
INSERT INTO controls_regulation_items SELECT * FROM _stage_controls_regulation_items;
DROP TABLE _stage_controls_regulation_items;

-- controls_framework_items
CREATE TEMP TABLE _stage_controls_framework_items (LIKE controls_framework_items);
\copy _stage_controls_framework_items FROM 'controls_framework_items.txt' WITH (FORMAT text)
DELETE FROM controls_framework_items WHERE id IN (SELECT id FROM _stage_controls_framework_items);
INSERT INTO controls_framework_items SELECT * FROM _stage_controls_framework_items;
DROP TABLE _stage_controls_framework_items;

-- program_regulations
CREATE TEMP TABLE _stage_program_regulations (LIKE program_regulations);
\copy _stage_program_regulations FROM 'program_regulations.txt' WITH (FORMAT text)
DELETE FROM program_regulations WHERE id IN (SELECT id FROM _stage_program_regulations);
INSERT INTO program_regulations SELECT * FROM _stage_program_regulations;
DROP TABLE _stage_program_regulations;

-- program_regulation_items
CREATE TEMP TABLE _stage_program_regulation_items (LIKE program_regulation_items);
\copy _stage_program_regulation_items FROM 'program_regulation_items.txt' WITH (FORMAT text)
DELETE FROM program_regulation_items WHERE id IN (SELECT id FROM _stage_program_regulation_items);
INSERT INTO program_regulation_items SELECT * FROM _stage_program_regulation_items;
DROP TABLE _stage_program_regulation_items;

-- versions
CREATE TEMP TABLE _stage_versions (LIKE versions);
\copy _stage_versions FROM 'versions.txt' WITH (FORMAT text)
DELETE FROM versions WHERE id IN (SELECT id FROM _stage_versions);
INSERT INTO versions SELECT * FROM _stage_versions;
DROP TABLE _stage_versions;

-- programs_frameworks
CREATE TEMP TABLE _stage_programs_frameworks (LIKE programs_frameworks);
\copy _stage_programs_frameworks FROM 'programs_frameworks.txt' WITH (FORMAT text)
DELETE FROM programs_frameworks WHERE id IN (SELECT id FROM _stage_programs_frameworks);
INSERT INTO programs_frameworks SELECT * FROM _stage_programs_frameworks;
DROP TABLE _stage_programs_frameworks;

-- programs_regulations
CREATE TEMP TABLE _stage_programs_regulations (LIKE programs_regulations);
\copy _stage_programs_regulations FROM 'programs_regulations.txt' WITH (FORMAT text)
DELETE FROM programs_regulations WHERE id IN (SELECT id FROM _stage_programs_regulations);
INSERT INTO programs_regulations SELECT * FROM _stage_programs_regulations;
DROP TABLE _stage_programs_regulations;

SET session_replication_role = origin;

-- Resetear sequences para que próximos INSERTs no choquen
SELECT setval(pg_get_serial_sequence('workspaces', 'id'), COALESCE((SELECT MAX(id) FROM workspaces), 1));
SELECT setval(pg_get_serial_sequence('program_categories', 'id'), COALESCE((SELECT MAX(id) FROM program_categories), 1));
SELECT setval(pg_get_serial_sequence('programs', 'id'), COALESCE((SELECT MAX(id) FROM programs), 1));
SELECT setval(pg_get_serial_sequence('framework_items', 'id'), COALESCE((SELECT MAX(id) FROM framework_items), 1));
SELECT setval(pg_get_serial_sequence('controls', 'id'), COALESCE((SELECT MAX(id) FROM controls), 1));
SELECT setval(pg_get_serial_sequence('regulations', 'id'), COALESCE((SELECT MAX(id) FROM regulations), 1));
SELECT setval(pg_get_serial_sequence('regulation_items', 'id'), COALESCE((SELECT MAX(id) FROM regulation_items), 1));
SELECT setval(pg_get_serial_sequence('policies', 'id'), COALESCE((SELECT MAX(id) FROM policies), 1));
SELECT setval(pg_get_serial_sequence('policy_regulation_item_mappings', 'id'), COALESCE((SELECT MAX(id) FROM policy_regulation_item_mappings), 1));
SELECT setval(pg_get_serial_sequence('controls_regulation_items', 'id'), COALESCE((SELECT MAX(id) FROM controls_regulation_items), 1));
SELECT setval(pg_get_serial_sequence('controls_framework_items', 'id'), COALESCE((SELECT MAX(id) FROM controls_framework_items), 1));
SELECT setval(pg_get_serial_sequence('program_regulations', 'id'), COALESCE((SELECT MAX(id) FROM program_regulations), 1));
SELECT setval(pg_get_serial_sequence('program_regulation_items', 'id'), COALESCE((SELECT MAX(id) FROM program_regulation_items), 1));
SELECT setval(pg_get_serial_sequence('versions', 'id'), COALESCE((SELECT MAX(id) FROM versions), 1));
SELECT setval(pg_get_serial_sequence('programs_frameworks', 'id'), COALESCE((SELECT MAX(id) FROM programs_frameworks), 1));
SELECT setval(pg_get_serial_sequence('programs_regulations', 'id'), COALESCE((SELECT MAX(id) FROM programs_regulations), 1));

COMMIT;

-- ─── post-import ───────────────────────────────────
-- 1. Patch scopes de la regulation: AB filtra el view
--    por scopes.admin_teams.all ∩ user.team_ids. Le
--    metemos TODOS los teams del local así cualquier
--    user la ve.
UPDATE regulations SET scopes = jsonb_build_object(
  'admin_teams', jsonb_build_object('all', (SELECT jsonb_agg(id) FROM teams)),
  'viewonly_teams', jsonb_build_object('all', (SELECT jsonb_agg(id) FROM teams))
) WHERE id IN (SELECT DISTINCT regulation_id FROM regulation_items);

-- 2. Refresh user_facts matview (permission cache)
REFRESH MATERIALIZED VIEW CONCURRENTLY user_facts;

\echo
\echo '✓ Import done. ACUERDATE de reiniciar el API node:'
\echo '   pkill -f "contexts/api/app.ts"   # nodemon lo reinicia solo'
\echo
